Include details about which module doesn't contain variables.
Example error:

```
>>> m = snt.nets.ResNet50(10)
>>> m.trainable_variables
...
ValueError: ResNet50(num_classes=10) does not currently contain any trainable_variables.

Most Sonnet modules create variables the first time they are called with an
input and requesting variables before this typically indicates a coding error.

You should refactor your code such that you request module variables after you
pass an example input to the module. For example:

    module = ResNet50(num_classes=10)
    output = module(input)
    params = module.trainable_variables

If the module is stateless consider using `snt.allow_empty_variables(module)` to
suppress this error:

    module = ResNet50(num_classes=10)
    snt.allow_empty_variables(module)
    params = module.trainable_variables
```

PiperOrigin-RevId: 272866557
Change-Id: I4547a36acdfe9afa17ee13ed09dc24fddbce1890